### PR TITLE
Add FAWE support

### PR DESCRIPTION
**Pull request by k-jiang**
Let BetonQuest supports FAWE-1.13

### CODE REVIEW

**Comment by bundabrg** [comment]
Nice I'll take a look soon as I can. Last time I used FAWE it was being a pain to compile against. Has that gotten better?

**Comment by k-jiang** [comment]
No.

Since FAWE modified the WorldEdit codes, you need to [force maven to use a FAWE's jar as dependency](https://github.com/bundabrg/BetonQuest/pull/15/commits/0f5ba8d2cd7f378535c71c2d822cb2160124cfcc#diff-82c08a7dc2a25a2c6f92d2b0a91c84c9R62) so you can run BQ with it. FAWE can't keep up with the newest WorldEdit API so it has its own "modified" WE API. Objects are in different types (class vs instance). If you don't supply or override the WE repository with FAWE.jar, running BQ with FAWE will get you [this](https://stackoverflow.com/questions/591411/java-error-found-interface-but-class-was-expected) even though your codes are exactly the same (as you compile BQ with vanilla WE).

Unfortunately you can't just put a maven link into the pom.xml. If you chose to force maven to compile with FAWE, you have to actually include a physical jar file into the project. That means, you have to manually update that FAWE.jar file every times when API changes happened in FAWE. And the FAWE team doesn't provide their custom WorldEdit maven at the moment (and I doubt they would).

To make things a little bit robust, I used [FAWE's own schematic-paste API](https://github.com/boy0001/FastAsyncWorldedit/wiki/Pasting-a-schematic) in this PR. But there is no way to completely avoid the modified-WorldEdit-API loophole, because [Vector API changed in vanilla WE](https://github.com/EngineHub/WorldEdit/commit/399e0ad5fa7637d5d3ccce7ead1ad409e85c7dd2) and FAWE have never updated it. So you still need to include the FAWE.jar.

This issue have been addressed multiple times. If you want to read more, check https://github.com/boy0001/FastAsyncWorldedit/issues/1193.

**Comment by bundabrg** [comment]
I'm happy to host the jar in my public maven repo which should help without needing to provide the jar with the project.

**Comment by k-jiang** [comment]
That would be great. But remember that the package name has to be `com.sk89q.worldedit`. Not sure if that will confuse people...

**Comment by bundabrg** [comment]
Hi, are you able to resubmit this PR against https://github.com/Co0sh/BetonQuest as I've now merged this preview there but still need a little time to review this PR properly. Sorry for the delay, time just seems to slip away sometimes.

**Comment by k-jiang** [comment]
Sorry for the late reply. I will look into it and try to submit a new one. It might takes some time cause there are so many changes happened since the last submission.

You can close this PR if you like.

**Pull request closed without merging**
